# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ahchcli < Formula
  desc ""
  homepage "https://github.com/amrhsyn/ahchcli/"
  version "11"

  on_macos do
    url "https://github.com/amrhsyn/ahchcli/releases/download/v11/ahchcli_11_darwin_all.tar.gz"
    sha256 "8ef84754c92d2534d375091427890d79e5509cf09eca0d2ae10a3f56c856f0a9"

    def install
      bin.install "ahchcli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amrhsyn/ahchcli/releases/download/v11/ahchcli_11_linux_arm64.tar.gz"
      sha256 "5c74e9ef77083cd82f439faa54b7ab4eabafc04b8c87d687b7db95ca3cbc03cb"

      def install
        bin.install "ahchcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/amrhsyn/ahchcli/releases/download/v11/ahchcli_11_linux_amd64.tar.gz"
      sha256 "356ad01dffe47f287129ab5519be7b85dc26aed94706ae6713fa6034f1783f10"

      def install
        bin.install "ahchcli"
      end
    end
  end
end
