# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ahchcli < Formula
  desc ""
  homepage "https://github.com/amrhsyn/ahchcli/"
  version "1.2"

  on_macos do
    url "https://github.com/amrhsyn/ahchcli/releases/download/v1.2/ahchcli_1.2_darwin_all.tar.gz"
    sha256 "52e0e1bb0a0540d8ae4fe59c1dc43b90a04a61a7fc7e6fe063033a2918ff1d64"

    def install
      bin.install "ahchcli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amrhsyn/ahchcli/releases/download/v1.2/ahchcli_1.2_linux_arm64.tar.gz"
      sha256 "765962dd83805983b05575f3f4116a235fffbfe4eba8bd5b82114dcf6eea31d7"

      def install
        bin.install "ahchcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/amrhsyn/ahchcli/releases/download/v1.2/ahchcli_1.2_linux_amd64.tar.gz"
      sha256 "260d91a7d806d3474f6a4d2ed852843feefdd217e6e4312a9757221fbef8e91d"

      def install
        bin.install "ahchcli"
      end
    end
  end
end
